name: Publish Package

on:
  release:
    types: [ created, edited ]
  workflow_dispatch:

jobs:
  build:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: lerna bootstrap
    - run: lerna run build
    - run: lerna publish from-git
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
