name: Release

on:
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ steps.get_version.outputs.version }}"
