name: Release Draft

on:
  push:
    branches: [ master ]

jobs:
  tagged-release:
    name: "Release Draft"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          draft: true
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "alpha"
          title: "alpha"
