name: Release Draft

on:
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  tagged-release:
    name: "Release Draft"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          draft: false
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
