name: Test Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm i
      - run: lerna run test:ci

      - uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: d7cc2b984737376a118b540a6aa72447f3fc6fbb705988584b33dd0c8fbcb856
        with:
          workingDirectory: ${{github.workspace}}/packages/vuito
